apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: docker-hello-google
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: docker-hello-google
    spec:
      containers:
      - image: us.gcr.io/gwii-cloud/hello:$CIRCLE_SHA1
        name: nginx
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /healthz
            port: 10254
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 5
        ports:
        - containerPort: 80
        - containerPort: 443
