version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: nginx -g "daemon off;"
    container_name: docker-hello-google
    environment:
      API_URL: http://localhost:8080
    ports:
      - "80:80"
